---
title: Write a Memorandum
linktitle: Write a Memorandum
menu:
  howto:
    parent: How To
    weight: 4
toc: true
type: docs
weight: 2
---

Memorandum writing is an acquired skill for urban planners. Memos are designed to be an efficient means of communicating information to a relatively general audience. Within planning, memos tend to be concise documents that may contain either requested information for staff or recommendations on how to proceed with a particular issue designed to be reviewed by decision-makers. Your memos should struve to be clear, concise, have a logical structure, and should contain well-designed illustrations and visualizations. Like any document you plan to share with others, your memos should adhere to proper formatting and should be free of grammatical and spelling errors.

Most memos include fewer citations than other academic writing, but when you choose to cite, please include citations as footnotes to reference material that is not your own work or ideas.

# Memo Writing Guidelines

- Assume that your audience has a basic level of technical and subject matter expertise.
- Begin with a heading that includes the name of the memo author, name of the memo recipient, date, and a descriptive subject.
- A memo is typically written in response to something. The first paragraph of the memo should describe what the memo is responding to, and should summarize what the writer of the memo has done to prepare the response. The first paragraph should also summarize any key findings or recommendations.
- Information within a memo should be organized in a logical fashion. Use section headings to help your audience find particular information easily.
- Make use of bullets and lists as an efficient way to convey information.
- General information should be presented first followed by more detailed information. As you support information with evidence, you should follow the same general progression of general to specific.
- Memos should conclude with a summary statement that encapsulates the key findings which you have developed. If you are providing recommendations in your memo, you may also want to re-state your recommendations here, and provide instructions or suggestions for how to follow up on your guidance.
- Because a memo is designed to be a concise document, you may have important extra information which would be useful to share with the memo's audience, but which does not fit within the main memorandum text. Such items can be included in an appendix or attachment to the memo, and should be references as apporpriate within the memo (e.g. "See the attached document in Appendix A for the property surveyor's description of the Holloway parcel").

# Memo Writing Resources

[Annotated Example Memorandum](/howto/howto/08-write_memo_files/Greenlee_Memo_Example.pdf)
[Professional Writing By the Numbers - Ed Feser](/howto/howto/08-write_memo_files/PWBTN_4.pdf)


